# -*- coding: utf-8 -*-
"""models

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZGuWvjKeuQnuS82dVZszoOnFBx6Z3fcN
"""

from pydantic import BaseModel
from typing import List

# для запроса на поиск
class SearchRequest(BaseModel):
    query: str
    index_type: str  # tfidf или embeddings

# для результатов поиска
class SearchResult(BaseModel):
    title: str
    overview: str
    score: float